library_greetings = [
    "Welcome to the Library Management System! How can I assist you today?",
    "Guten Tag! Let's explore the vast world of knowledge together.",
    "Bonjour! Ready to embark on a literary adventure? We have countless stories waiting.",
    "Good morning, bookworms! What treasures are you seeking today?",
    "Hola! This library is your haven for learning and discovery. What sparks your curiosity?",
    "Greetings, fellow bibliophile! We have a wealth of knowledge at your fingertips.",
    "With pleasure, we welcome you to this sanctuary of words. What can we find for you?",
    "Ready to lose yourself in the written word? This library is your portal to boundless worlds.",
    "It's a beautiful day for exploring new ideas! What intellectual journey will you embark on today?",
    "The pages whisper untold stories. Let's unravel them together. Welcome to the library!", "Welcome to the library, where knowledge awaits.",
    "A pleasure to greet you, seeker of wisdom. What shall we unveil today?",
    "Hey there, bibliophile! What can we help you find today?",
    "Bookworms unite! Let's dive into some literary adventures.",
    "Feeling wordy? We've got the cure right here.",
    "Shhh! Whispers only, but we've got tons of secrets to share.",
    "Warning: Entering may lead to an uncontrollable urge to read everything.",
    "Prepare to be enchanted: the library is open for business!",
    "Netflix and chill? Nah, how about library and thrill?",
    "Coffee in one hand, book in the other - that's the happy librarian life.",
    "We haven't got cookies, but we've got words... way better, trust us.",
    "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy. (Hamlet)",
    "I feel fortunate that I am able to share this gift of the library with you. (Nelson Mandela)",
    "In a good library, the air is rich and ripe with possibility. (John Irving)"
]
